# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
from qcware import forge
# this line is for internal tracking; it is not necessary for use!
forge.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# forge.config.set_api_key('paste API key here')
import numpy as np

In [2]:
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

forge.qutils.qdot(a, b)

-0.024295126587962623

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 24.177814782439462
a dot b with qdot: 23.943705142351277


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[0.64299138 0.9504055  0.71077966 0.57159086]
 [1.18427951 1.46460205 1.08888671 0.95564921]
 [1.22660684 1.80707977 1.55162376 0.78738906]
 [1.57307154 1.71284552 1.87884034 1.19012661]]

qdot matrix product:
 [[0.63748965 0.93403398 0.7036872  0.55526557]
 [1.19057471 1.45293454 1.05472874 0.90482465]
 [1.22856119 1.81139813 1.53332568 0.76106712]
 [1.53929133 1.64935665 1.88401793 1.21324653]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
forge.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# forge.qutils.qdot(a, b, backend='awsbraket/ionq')