# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
import qcware.config
# this line is for internal tracking; it is not necessary for use!
qcware.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# qcware.config.set_api_key('paste API key here')
import numpy as np

In [2]:
import qcware.qutils
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

qcware.qutils.qdot(a, b)

2.220446049250313e-16

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = qcware.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 22.117432704624054
a dot b with qdot: 22.117432704624065


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = qcware.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[1.02778337 0.44334583 0.71261274 0.95318995]
 [1.36743726 0.70449022 1.15621292 1.20416488]
 [0.6672213  0.67860939 0.98985704 0.66367114]
 [1.19732563 0.69212647 1.05370997 1.05701274]]

qdot matrix product:
 [[1.02778337 0.44334583 0.71261274 0.95318995]
 [1.36743726 0.70449022 1.15621292 1.20416488]
 [0.6672213  0.67860939 0.98985704 0.66367114]
 [1.19732563 0.69212647 1.05370997 1.05701274]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
qcware.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# qcware.qutils.qdot(a, b, backend='awsbraket/ionq')