# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
from qcware import forge
# this line is for internal tracking; it is not necessary for use!
forge.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# qcware.config.set_api_key('paste API key here')
import numpy as np

In [2]:
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

forge.qutils.qdot(a, b)

0.001998003990027808

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 24.968745153656158
a dot b with qdot: 24.609888546604346


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[1.16542678 0.65064164 0.46849837 0.43607396]
 [0.82793032 0.38297031 0.28478394 0.38049149]
 [0.93071459 0.54596587 0.38088184 0.3655308 ]
 [1.31322575 0.66148395 0.4009124  0.81703758]]

qdot matrix product:
 [[1.15833041 0.62242135 0.47973874 0.48850205]
 [0.82527165 0.38611165 0.28937859 0.3899554 ]
 [0.92638212 0.52279642 0.39270814 0.37235605]
 [1.27300112 0.68894928 0.38827063 0.81802899]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
forge.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# qcware.qutils.qdot(a, b, backend='awsbraket/ionq')