# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
from qcware import forge
# this line is for internal tracking; it is not necessary for use!
forge.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# forge.config.set_api_key('paste API key here')
import numpy as np

In [2]:
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

forge.qutils.qdot(a, b)

-0.014099396490701022

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 22.927829208768163
a dot b with qdot: 22.400634645578094


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[0.41463992 1.47530542 0.75371437 1.00675823]
 [0.69921899 0.8775592  0.85252927 0.97741369]
 [0.39671121 0.58216806 0.35637821 0.66071307]
 [0.34925214 0.77469598 0.68564608 0.65986241]]

qdot matrix product:
 [[0.38783608 1.48481057 0.76706581 1.04870173]
 [0.69483459 0.8757715  0.86394299 0.98493025]
 [0.39873566 0.58330822 0.34428547 0.67664984]
 [0.35321468 0.75077881 0.66362637 0.66898485]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
forge.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# forge.qutils.qdot(a, b, backend='awsbraket/ionq')