# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
from qcware import forge
# this line is for internal tracking; it is not necessary for use!
forge.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# forge.config.set_api_key('paste API key here')
import numpy as np

In [2]:
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

forge.qutils.qdot(a, b)

0.003992031840890586

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 26.599024953956388
a dot b with qdot: 26.267869318554176


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[1.39742896 0.80536798 0.89412701 1.18686866]
 [1.84547554 1.24043804 1.24497081 1.82891696]
 [1.11009653 0.38752782 0.41574017 1.0680593 ]
 [2.39355333 1.06642484 1.27962559 1.99702434]]

qdot matrix product:
 [[1.36629638 0.80700078 0.90462677 1.22756044]
 [1.87770774 1.25277048 1.22956015 1.83036654]
 [1.10725823 0.38158011 0.42689281 1.07401204]
 [2.39276262 1.06102115 1.32506432 1.9800461 ]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
forge.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# forge.qutils.qdot(a, b, backend='awsbraket/ionq')