# Quantum Dot Product

This notebook demonstrates our `qdot` quantum dot product API call which performs general matrix multiplication with a NISQ quantum algorithm. We expect the quantum dot product to be faster than classical dot products for high dimensional vectors as quantum hardware matures.

### Basic usage

In [1]:
from qcware import forge
# this line is for internal tracking; it is not necessary for use!
forge.config.set_environment_source_file('qdot.ipynb')

# Paste your API key below if not using Forge hosted notebooks
# qcware.config.set_api_key('paste API key here')
import numpy as np

In [2]:
# Dot product of 2-D vectors:
a = np.array([1., 0.])
b = np.array([0., 1.])

forge.qutils.qdot(a, b)

-0.01005050633883342

In [3]:
# qdot with larger vectors:
a = np.random.rand(100)
b = np.random.rand(100)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)

print('a dot b using numpy:', numpy_result)
print('a dot b with qdot:', qdot_result)

a dot b using numpy: 24.41505329019486
a dot b with qdot: 24.076632066130884


### Matrix multiplication

`qdot` can be used for matrix multiplication more generally. It's therefore a great way to use quantum computing for many linear algebra applications.

In [4]:
# qdot with larger vectors:
n = 4
a = np.random.rand(n, n)
b = np.random.rand(n, n)

numpy_result = np.dot(a, b)
qdot_result = forge.qutils.qdot(a, b)


print('numpy matrix product:\n', numpy_result)
print('\nqdot matrix product:\n', qdot_result)

numpy matrix product:
 [[1.31457938 1.52666578 2.19772447 1.51460235]
 [0.86936112 0.80768381 1.33525594 0.93392517]
 [0.96129044 0.62875329 1.36758971 0.93396264]
 [1.19040633 1.1994427  1.87734733 1.34761914]]

qdot matrix product:
 [[1.30958577 1.53516462 2.1969258  1.5212137 ]
 [0.8689746  0.80520232 1.32975422 0.94265312]
 [0.98015185 0.63425903 1.37591964 0.92061066]
 [1.19766453 1.1829742  1.87652638 1.32328189]]


### Running on quantum hardware

Physical quantum hardware can be used by specifying the `backend` argument. Here we use `qdot` with IonQ's trapped ion technology.

In [5]:
# Uncomment to use next available scheduling:
forge.config.set_scheduling_mode("next_available")

a = np.random.rand(3)
b = np.random.rand(3)

# Uncomment this line to perform hardware run:
# qcware.qutils.qdot(a, b, backend='awsbraket/ionq')